import type { Calculator } from "@workspace/api-client-react";

export const calculatorsRegistry: Calculator[] = [
  // Math
  {
    slug: "percentage",
    name: "Percentage Calculator",
    description: "Calculate percentages, percentage change, and more.",
    category: "Math",
    categorySlug: "math",
    icon: "Percent",
    tags: ["math", "percent", "fraction"],
    isFeatured: true,
  },
  {
    slug: "fraction",
    name: "Fraction Calculator",
    description: "Add, subtract, multiply, and divide fractions.",
    category: "Math",
    categorySlug: "math",
    icon: "DivideSquare",
    tags: ["math", "fraction", "divide"],
  },
  {
    slug: "average",
    name: "Average Calculator",
    description: "Find the mean, median, and mode of a set of numbers.",
    category: "Math",
    categorySlug: "math",
    icon: "BarChart",
    tags: ["math", "average", "mean", "median"],
  },
  {
    slug: "exponent",
    name: "Exponent Calculator",
    description: "Calculate exponents and powers.",
    category: "Math",
    categorySlug: "math",
    icon: "Superscript",
    tags: ["math", "power", "exponent"],
  },
  {
    slug: "scientific",
    name: "Scientific Calculator",
    description: "Advanced mathematical functions.",
    category: "Math",
    categorySlug: "math",
    icon: "Calculator",
    tags: ["math", "scientific", "trigonometry"],
  },
  // Finance
  {
    slug: "mortgage",
    name: "Mortgage Calculator",
    description: "Estimate your monthly mortgage payments.",
    category: "Finance",
    categorySlug: "finance",
    icon: "Home",
    tags: ["finance", "loan", "mortgage", "house"],
    isFeatured: true,
  },
  {
    slug: "compound-interest",
    name: "Compound Interest",
    description: "Calculate how your money grows over time.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    tags: ["finance", "interest", "investment", "growth"],
    isFeatured: true,
  },
  {
    slug: "loan",
    name: "Loan Calculator",
    description: "Calculate loan payments and total interest.",
    category: "Finance",
    categorySlug: "finance",
    icon: "Banknote",
    tags: ["finance", "loan", "debt", "interest"],
  },
  {
    slug: "roi",
    name: "ROI Calculator",
    description: "Calculate Return on Investment.",
    category: "Finance",
    categorySlug: "finance",
    icon: "LineChart",
    tags: ["finance", "roi", "investment", "profit"],
  },
  {
    slug: "savings",
    name: "Savings Calculator",
    description: "Plan your savings goals.",
    category: "Finance",
    categorySlug: "finance",
    icon: "PiggyBank",
    tags: ["finance", "savings", "goal", "money"],
  },
  {
    slug: "tip",
    name: "Tip Calculator",
    description: "Calculate tip and split the bill.",
    category: "Finance",
    categorySlug: "finance",
    icon: "Receipt",
    tags: ["finance", "tip", "restaurant", "split"],
  },
  {
    slug: "currency",
    name: "Currency Converter",
    description: "Convert between different currencies.",
    category: "Finance",
    categorySlug: "finance",
    icon: "DollarSign",
    tags: ["finance", "currency", "money", "exchange"],
  },
  // Health
  {
    slug: "bmi",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index.",
    category: "Health",
    categorySlug: "health",
    icon: "Activity",
    tags: ["health", "bmi", "weight", "fitness"],
    isFeatured: true,
  },
  {
    slug: "calorie",
    name: "Calorie Calculator",
    description: "Estimate daily calorie needs.",
    category: "Health",
    categorySlug: "health",
    icon: "Flame",
    tags: ["health", "calories", "diet", "nutrition"],
  },
  {
    slug: "ideal-weight",
    name: "Ideal Weight",
    description: "Calculate your ideal body weight.",
    category: "Health",
    categorySlug: "health",
    icon: "Scale",
    tags: ["health", "weight", "fitness"],
  },
  {
    slug: "body-fat",
    name: "Body Fat Calculator",
    description: "Estimate your body fat percentage.",
    category: "Health",
    categorySlug: "health",
    icon: "User",
    tags: ["health", "fat", "fitness", "body"],
  },
  {
    slug: "pregnancy",
    name: "Pregnancy Due Date",
    description: "Calculate estimated due date.",
    category: "Health",
    categorySlug: "health",
    icon: "Baby",
    tags: ["health", "pregnancy", "baby", "date"],
  },
  // Unit Conversion
  {
    slug: "length",
    name: "Length Converter",
    description: "Convert length and distance units.",
    category: "Unit Conversion",
    categorySlug: "conversion",
    icon: "Ruler",
    tags: ["conversion", "length", "distance", "measure"],
  },
  {
    slug: "weight",
    name: "Weight Converter",
    description: "Convert weight and mass units.",
    category: "Unit Conversion",
    categorySlug: "conversion",
    icon: "Weight",
    tags: ["conversion", "weight", "mass", "scale"],
  },
  {
    slug: "temperature",
    name: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin.",
    category: "Unit Conversion",
    categorySlug: "conversion",
    icon: "Thermometer",
    tags: ["conversion", "temperature", "celsius", "fahrenheit"],
  },
  {
    slug: "area",
    name: "Area Converter",
    description: "Convert area units.",
    category: "Unit Conversion",
    categorySlug: "conversion",
    icon: "Square",
    tags: ["conversion", "area", "space"],
  },
  {
    slug: "speed",
    name: "Speed Converter",
    description: "Convert speed units.",
    category: "Unit Conversion",
    categorySlug: "conversion",
    icon: "Gauge",
    tags: ["conversion", "speed", "velocity"],
  },
  // Date & Time
  {
    slug: "age",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days.",
    category: "Date & Time",
    categorySlug: "date",
    icon: "CalendarHeart",
    tags: ["date", "time", "age", "birthday"],
  },
  {
    slug: "date-diff",
    name: "Date Difference",
    description: "Calculate the time between two dates.",
    category: "Date & Time",
    categorySlug: "date",
    icon: "CalendarDays",
    tags: ["date", "time", "difference", "duration"],
  },
  {
    slug: "time-zone",
    name: "Time Zone Converter",
    description: "Convert time between different time zones.",
    category: "Date & Time",
    categorySlug: "date",
    icon: "Globe",
    tags: ["date", "time", "timezone", "world"],
  },
  // Statistics
  {
    slug: "mean-median-mode",
    name: "Mean, Median & Mode",
    description: "Calculate central tendency of a dataset.",
    category: "Statistics",
    categorySlug: "statistics",
    icon: "Sigma",
    tags: ["statistics", "math", "mean", "median", "mode"],
  },
  {
    slug: "standard-deviation",
    name: "Standard Deviation",
    description: "Calculate standard deviation and variance.",
    category: "Statistics",
    categorySlug: "statistics",
    icon: "BarChart2",
    tags: ["statistics", "math", "deviation", "variance"],
  },
  {
    slug: "probability",
    name: "Probability Calculator",
    description: "Calculate basic probabilities.",
    category: "Statistics",
    categorySlug: "statistics",
    icon: "Dices",
    tags: ["statistics", "math", "probability", "chance"],
  }
];
